---
abstract: 'Request reproducable hash keys order within a script and verify if Perl complies'
author:
  - 'Mike Schilli <m@perlmeister.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-HashKeyOrderBrokenAgain
no_index:
  directory:
    - t
    - inc
requires:
  Test::Simple: 0.31
resources:
  repository: http://github.com/mschilli/acme-hashkeyorderbrokenagain-perl
version: 0.01
